@isTest(seeAllData=false)
private class DisableApplicantProtalAccess_Test {

 /*   @testSetup static void setupData(){
        
    }
    
    private static testMethod void testContructor1(){
        System.Test.StartTest();
            Application__c app = [select id, Admission_Status__c from Application__c where Applications__c = 'Applications963963'];
            app.Admission_Status__c = 'Enrolled';
            update app;
        System.Test.StopTest();
    }*/

}