public class DropboxJSONClass {
  
   /* public String read_only{get;set;}
    public String hash{get;set;}
    public String interevision{get;set;}
    public String bytes{get;set;}
    public String thumb_exists{get;set;}
    public String rev{get;set;}
    public String modified{get;set;}
    public String size{get;set;}
    public String path{get;set;}
    public String is_dir{get;set;}
    public String root{get;set;}
    public String icon{get;set;}
    public List<contents> contents{get;set;}
    public List<modifier> modifier{get;set;}
    public class contents{
        public String rev{get;set;}
        public String thumb_exists{get;set;}
        public String path{get;set;}
        public String is_dir{get;set;}
        public String client_mtime{get;set;}
        public String icon{get;set;}
        public String read_only{get;set;}
        public String bytes{get;set;}
        public String modified{get;set;}
        public String size{get;set;}
        public String root{get;set;}
        public String mime_type{get;set;}
        public String revision{get;set;}
    }
    public static DropboxJSONClass parse(String json){
        return (DropboxJSONClass) System.JSON.deserialize(json, DropboxJSONClass.class);
    }
    
    public class modifier{
        public String email_verified{get;set;}
        public String display_name{get;set;}
        public String uid{get;set;}
        public String email{get;set;}
    }*/
}