@isTest(SeeAllData=true)

    public class FLAME_UtilityTestClass {

     /*   public static testMethod void testMyController_1() {
        PageReference pageRef = Page.EducationAndWorkDetails;
        Test.setCurrentPage(pageRef);
        
        Account acc = new Account(Name = 'FLAME 2016-17 Admissions');
       // insert acc;
        
        Test.startTest();
         Contact con = new Contact(FirstName = 'Testing',LastName = 'Extentia',Email =  'rohit63419FLAMETEST@gmail.com',AccountId = acc.Id );
         insert con;
        */
      /*  FLAME_Utility  controller = new FLAME_Utility ();
        controller.addHealth();
        controller.getHtmlText();
        controller.getHtmlText1();
        controller.getHtmlText2();
        controller.getPrograms1();*/
       
      // FLAME_Utility.getConactInfoByEmail(con.email);
       // Test.stopTest();
       // }
        }