Public Class PersonalDetails
{
        Public String Contactid{get;set;}
        Public String Salutation{get;set;}
        Public String FirstName{get;set;}
        Public String LastName{get;set;}
        Public String ConEmail{get;set;}
        Public String Age     {get;set;}     
        
        Public String Alternate_Email_ID {get;set;}
        
        Public String Analytics_Registration_Status  {get;set;}
        
        Public String FU_Applicant_Mailing_City  {get;set;}
        
        Public String FU_Applicant_Mailing_Country   {get;set;}
        
        Public String FU_Applicant_Mailing_State {get;set;}
        
        Public String FU_Applicant_Other_City    {get;set;}
        
        Public String FU_Applicant_Other_Country {get;set;}
        
        Public String FU_Applicant_Other_State {get;set;}    
        
        Public String Are_you_an_Indian {get;set;}
            
        
        Public String Cheque_Dispatch_Status {get;set;}
        
        Public String Classfication_ExFaculty {get;set;} 
        
        Public String Classfication_ExStaff  {get;set;}
        
        Public String Classfication_Faculty  {get;set;}
        
        Public String Classfication_FIL  {get;set;}
        
        Public String Classfication_Guest {get;set;} 
        
        Public String Classfication_Staff    {get;set;}
        
        Public String Classfication_Vendor   {get;set;}
        
        Public String Classfication_VIP  {get;set;}
        
        Public String Classfication_Withdrawn {get;set;} 
        
        Public String Classification_Alumni  {get;set;}
        
        Public String Classification_Applicant   {get;set;}
        
        Public String Classification_Student {get;set;}
        
        Public String Company_Institute_City {get;set;}
        
        Public String Completed_Exit_Interview   {get;set;}
        
        Public String Contact_Admission_Status {get;set;}    
        
        Public String CVUE_Student_Number    {get;set;}
        
        Public String Date_of_Joining    {get;set;}
        
        Public String Department      {get;set;} 
        
        Public String Designation_Name   {get;set;}
        
        Public String Detailed_Explanation   {get;set;}  
        
        Public String Employee_Id    {get;set;}
        
        Public String Employee_Name_del  {get;set;}
        
        Public String Father_s_Current_Company  {get;set;}
        
        Public String Father_s_Designation   {get;set;}
        
        Public String Father_s_Email_ID  {get;set;}
        
        Public String Father_s_First_Name    {get;set;}
        
        Public String Father_s_Last_Company  {get;set;}
        
        Public String Father_s_Last_Name {get;set;}
        
        Public String Father_s_Mobile_No {get;set;}
        
        Public String FUA_Father_s_Mobile_No {get;set;}
        
        Public String Father_s_Mobile_No_Code {get;set;} 
        
        Public String Father_s_Occupation    {get;set;}  
        
        Public String Gender     {get;set;}  
        
        Public String vbGrade_Name   {get;set;}      
        
        Public String Mailing_Address    {get;set;}
        
        Public String Mailing_Address_Line_1 {get;set;}
        
        Public String Mailing_Address_Line_2 {get;set;}
        
        Public String Mailing_City   {get;set;}
        
        Public String Mailing_Postal_Code {get;set;}     
        
        Public String Major  {get;set;}      
        
        Public String Marital_Status {get;set;}
        
        Public String Middle_Name {get;set;}         
        
        Public String Minor  {get;set;}  
        
        Public String FUA_Mobile     {get;set;}  
        
        Public String FU_Mobile_Phone_Code   {get;set;}
        
        Public String Mother_s_Current_Company   {get;set;}
        
        Public String Mother_s_Designation   {get;set;}
        
        Public String Mother_s_Email_ID  {get;set;}
        
        Public String Mother_s_First_Name    {get;set;}
        
        Public String Mother_s_Last_Company {get;set;}
        
        Public String Mother_s_Last_Name {get;set;}
        
        Public String Mother_s_Mobile_No {get;set;}
        
        Public String FUA_Mother_s_Mobile_No {get;set;}
        
        Public String Mother_s_Mobile_No_Code    {get;set;}
        
        Public String Mother_s_Occupation    {get;set;}
        
        Public String Mother_Tongue  {get;set;}
        
        Public String No_of_Feilds   {get;set;}  
        
        Public String Organization_Unit_Name {get;set;}
        
        Public String Other  {get;set;}
        
        Public String Other_City {get;set;}
        Public String FU_Outside_India {get;set;}    
        Public String Passport_Expiry_Date {get;set;}    
        Public String Passport_Issued_By {get;set;}
        Public String Passport_No    {get;set;}
        Public String Permanent_Address_Line_1   {get;set;}
        Public String Permanent_Address_Line_2 {get;set;}    
        Public String Permanent_Postal_Code  {get;set;}
        Public String Place_of_Birth {get;set;}
        Public String Portal_password    {get;set;}
        Public String Primary_Community_Profile  {get;set;}
        Public String Primary_Contact_Type   {get;set;}
        Public String Primary_Role   {get;set;}
        Public String Problem_Under_Department   {get;set;}
        Public String Program_Interested {get;set;}
        Public String Program_Interested_In {get;set;}   
        Public String Program_Version    {get;set;}
        Public String Reg_Completed  {get;set;}
        Public String Reg_General_Info_Completed {get;set;}
        Public String Reg_Interests_Completed {get;set;} 
        Public String Registration_Status {get;set;} 
        Public String Reg_Picture_Completed  {get;set;}
        Public String Reg_T_C_Completed  {get;set;}
        Public String Religion   {get;set;}  
        
        Public String FU_Residence_Phone_Code    {get;set;}
        Public String Residence_Phone_No {get;set;}
        Public String FUA_Residence_Phone_No {get;set;}
        Public String Save_Withdrawal_Application {get;set;} 
        Public String Source     {get;set;}      
        Public String Student_s_Alternate_Email  {get;set;}
        Public String Student_s_Contact_Number   {get;set;} 
        Public String Student_Withdrawal_Completion{get;set;}    
        Public String test   {get;set;}
        Public String Total_Family_Income{get;set;}  
        Public String Visa_Status    {get;set;}
        Public String Website    {get;set;}
        Public String Withdrawal_Details_Comments{get;set;}  
        Public String Withdrawal_Primary_Reason  {get;set;}
        Public String Withdrawal_Request_Date    {get;set;}
        
        Public Date BirthdateValue {get;set;}
        Public Date  PassportExpireDateValue {get;set;}
        
        Public String PlaceOfBirthCon{get;set;}
        Public String PlaceOfBirthSt{get;set;}
        Public String PlaceOfBirthOut{get;set;}
    
}